// src/lib/farmacos.js
// Catálogo de fármacos pediátricos — fonte única (T2 etapa 2a).
// Extraído LITERALMENTE de src/modulos/pedfarma.jsx: nenhum valor clínico
// alterado, arredondado ou reordenado. Cada entrada mantém o objeto `calc`
// consumido por calcularDose (Harriet Lane / SBP).

export const DRUGS = [
  // ─── Antibióticos ───────────────────────────────────────────────────────────
  { id:"amoxicilina",     cat:"Antibiótico", nome:"Amoxicilina",                 via:"VO",    dose:"40–90 mg/kg/dia",   freq:"8/8h ou 12/12h",  max:"3 g/dia",   obs:"90 mg/kg/dia para pneumonia/otite de alto risco · Suspensão 250mg/5mL ou 400mg/5mL", calc:{min:40,max:90,unidade:"dia",tomadas:[2,3],tetoMg:3000,tetoTipo:"dia",susp:[{label:"250 mg/5 mL",mgPer5:250,tomadas:3,freqLabel:"8/8h"},{label:"400 mg/5 mL",mgPer5:400,tomadas:2,freqLabel:"12/12h"}]} },
  { id:"amoxiclav",       cat:"Antibiótico", nome:"Amoxicilina+Clavulanato",     via:"VO",    dose:"40–90 mg/kg/dia (fração amox)", freq:"8/8h ou 12/12h",   max:"3 g/dia",   obs:"Dose pela fração amoxicilina (igual à amoxicilina). 250 mg/5 mL: 8/8h · 400 mg/5 mL: 12/12h · Alta dose (90 mg/kg/dia) preferir formulação 400 (ES) pela menor carga de clavulanato", calc:{min:40,max:90,unidade:"dia",tomadas:[2,3],tetoMg:3000,tetoTipo:"dia",susp:[{label:"250/62,5 por 5 mL (amox 250)",mgPer5:250,tomadas:3,freqLabel:"8/8h"},{label:"400/57 por 5 mL (amox 400)",mgPer5:400,tomadas:2,freqLabel:"12/12h"}]} },
  { id:"azitromicina",    cat:"Antibiótico", nome:"Azitromicina",                via:"VO",    dose:"10 mg/kg/dia",       freq:"1x/dia",          max:"500 mg/dia",obs:"Dose única diária por 3–5 dias · Faringite, pneumonia atípica", calc:{min:10,max:10,unidade:"dia",tomadas:[1],tetoMg:500,tetoTipo:"dia",susp:[{label:"200 mg/5 mL",mgPer5:200,tomadas:1,freqLabel:"1x/dia"}]} },
  { id:"claritromicina",  cat:"Antibiótico", nome:"Claritromicina",              via:"VO",    dose:"15 mg/kg/dia",       freq:"12/12h",          max:"1 g/dia",   obs:"Atípicos, H. pylori, pertussis", calc:{min:15,max:15,unidade:"dia",tomadas:[2],tetoMg:1000,tetoTipo:"dia",susp:[{label:"250 mg/5 mL",mgPer5:250,tomadas:2,freqLabel:"12/12h"}]} },
  { id:"cefalexina",      cat:"Antibiótico", nome:"Cefalexina",                  via:"VO",    dose:"25–100 mg/kg/dia",   freq:"6/6h ou 8/8h",    max:"4 g/dia",   obs:"1ª geração · Infecções cutâneas, ITU não complicada", calc:{min:25,max:100,unidade:"dia",tomadas:[3,4],tetoMg:4000,tetoTipo:"dia",susp:[{label:"250 mg/5 mL",mgPer5:250,tomadas:4,freqLabel:"6/6h"}]} },
  { id:"ceftriaxona",     cat:"Antibiótico", nome:"Ceftriaxona",                 via:"IV/IM", dose:"50–100 mg/kg/dia",   freq:"1x/dia",          max:"4 g/dia",   obs:"100 mg/kg para meningite · Diluir em 100 mL SF · Infundir em 30–60 min", calc:{min:50,max:100,unidade:"dia",tomadas:[1],tetoMg:4000,tetoTipo:"dia",susp:[]} },
  { id:"cefuroxima",      cat:"Antibiótico", nome:"Cefuroxima",                  via:"VO",    dose:"20–30 mg/kg/dia",    freq:"12/12h",          max:"500 mg/dose",obs:"2ª geração · Sinusite, pneumonia leve", calc:{min:20,max:30,unidade:"dia",tomadas:[2],tetoMg:500,tetoTipo:"dose",susp:[{label:"250 mg/5 mL",mgPer5:250,tomadas:2,freqLabel:"12/12h"}]} },
  { id:"tmpsmt",          cat:"Antibiótico", nome:"Sulfametoxazol + TMP",        via:"VO",    dose:"8–12 mg/kg/dia (TMP)",freq:"12/12h",         max:"160 mg TMP/dose",obs:"ITU · Pneumocistose: 15–20 mg/kg/dia TMP · Evitar < 2 meses", calc:{min:8,max:12,unidade:"dia",tomadas:[2],tetoMg:160,tetoTipo:"dose",susp:[{label:"TMP 40 mg/5 mL",mgPer5:40,tomadas:2,freqLabel:"12/12h"}]} },
  { id:"metronidazol",    cat:"Antibiótico", nome:"Metronidazol",                via:"VO/IV", dose:"30 mg/kg/dia",       freq:"8/8h",            max:"2 g/dia",   obs:"Giardia, ameba, Clostridioides, anaeróbios · IV: infundir em 30–60 min", calc:{min:30,max:30,unidade:"dia",tomadas:[3],tetoMg:2000,tetoTipo:"dia",susp:[{label:"200 mg/5 mL (benzoil)",mgPer5:200,tomadas:3,freqLabel:"8/8h"}]} },
  { id:"clindamicina",    cat:"Antibiótico", nome:"Clindamicina",                via:"VO/IV", dose:"20–40 mg/kg/dia",    freq:"6/6h ou 8/8h",    max:"1,8 g/dia", obs:"MRSA comunitário, celulite periorbitária · Monitorar colite pseudomembranosa", calc:{min:20,max:40,unidade:"dia",tomadas:[3,4],tetoMg:1800,tetoTipo:"dia",susp:[{label:"75 mg/5 mL",mgPer5:75,tomadas:4,freqLabel:"6/6h"}]} },
  { id:"penicvk",         cat:"Antibiótico", nome:"Fenoximetilpenicilina (Pen V)", via:"VO",  dose:"25–50 mg/kg/dia",    freq:"6/6h ou 8/8h",    max:"3 g/dia",   obs:"Faringite estreptocócica, escarlatina · Administrar em jejum", calc:{min:25,max:50,unidade:"dia",tomadas:[3,4],tetoMg:3000,tetoTipo:"dia",susp:[{label:"250 mg/5 mL",mgPer5:250,tomadas:4,freqLabel:"6/6h"}]} },
  { id:"nitrofurantoina", cat:"Antibiótico", nome:"Nitrofurantoína",             via:"VO",    dose:"5–7 mg/kg/dia",      freq:"6/6h",            max:"400 mg/dia",obs:"ITU baixa · NÃO usar < 3 meses · Profilaxia: 1–2 mg/kg/dia", calc:{min:5,max:7,unidade:"dia",tomadas:[4],tetoMg:400,tetoTipo:"dia",susp:[{label:"25 mg/5 mL",mgPer5:25,tomadas:4,freqLabel:"6/6h"}]} },
  // ─── Analgésicos/Antipiréticos ──────────────────────────────────────────────
  { id:"paracetamol",     cat:"Analgésico",  nome:"Paracetamol (Acetaminofeno)", via:"VO/VR", dose:"10–15 mg/kg/dose",   freq:"6/6h",       max:"75 mg/kg/dia ou 4 g/dia", obs:"Intervalo mínimo 4h · VR: 20 mg/kg/dose · Acetilcisteína se superdose > 150 mg/kg", calc:{min:10,max:15,unidade:"dose",tomadasDiaMax:4,tetoMgDia:4000,susp:[{label:"Gotas 200 mg/mL",mgPerMl:200,gotas:true},{label:"Suspensão 32 mg/mL",mgPerMl:32}]} },
  { id:"dipirona",        cat:"Analgésico",  nome:"Dipirona (Metamizol)",        via:"VO/IV", dose:"10–15 mg/kg/dose",   freq:"6/6h",            max:"1 g/dose",  obs:"IV: infundir lentamente (risco de hipotensão) · Evitar < 3 meses de vida", calc:{min:10,max:15,unidade:"dose",tomadasDiaMax:4,tetoMg:1000,tetoTipo:"dose",susp:[{label:"Gotas 500 mg/mL",mgPerMl:500,gotas:true},{label:"Solução 50 mg/mL",mgPerMl:50}]} },
  { id:"ibuprofeno",      cat:"Analgésico",  nome:"Ibuprofeno",                  via:"VO",    dose:"5–10 mg/kg/dose",    freq:"6/6h–8/8h",       max:"40 mg/kg/dia", obs:"Com alimentos · Evitar em desidratados, < 6 meses, varicela · Contraindicado em dengue", calc:{min:5,max:10,unidade:"dose",tomadasDiaMax:4,tetoMgKgDia:40,susp:[{label:"Gotas 100 mg/mL",mgPerMl:100,gotas:true},{label:"Suspensão 20 mg/mL",mgPerMl:20}]} },
  // ─── Anti-inflamatórios / Corticoides ──────────────────────────────────────
  { id:"prednisolona",    cat:"Corticoide",  nome:"Prednisolona",                via:"VO",    dose:"1–2 mg/kg/dia",      freq:"1x/dia",          max:"40–60 mg/dia",obs:"Asma: 1–2 mg/kg/dia 3–5 dias · APLV: 1 mg/kg/dia · Dose única matinal", calc:{min:1,max:2,unidade:"dia",tomadas:[1],tetoMg:60,tetoTipo:"dia",susp:[]} },
  { id:"dexametasona",    cat:"Corticoide",  nome:"Dexametasona",                via:"VO/IM/IV", dose:"0,15–0,6 mg/kg/dia", freq:"1x/dia",      max:"10 mg/dia", obs:"Crupe: 0,15–0,6 mg/kg dose única · Meningite bacteriana: 0,15 mg/kg 6/6h × 4 dias", calc:{min:0.15,max:0.6,unidade:"dia",tomadas:[1],tetoMg:10,tetoTipo:"dia",susp:[]} },
  { id:"hidrocortisona",  cat:"Corticoide",  nome:"Hidrocortisona",              via:"IV",    dose:"5–10 mg/kg/dose",    freq:"6/6h",            max:"300 mg/dose",obs:"Asma grave, insuficiência adrenal, choque séptico refratário a vasopressor", calc:{min:5,max:10,unidade:"dose",tomadasDiaMax:4,tetoMg:300,tetoTipo:"dose",susp:[]} },
  { id:"budesonida",      cat:"Corticoide",  nome:"Budesonida inalatória",       via:"INH",   dose:"100–400 mcg/dia",    freq:"2x/dia",          max:"800 mcg/dia",obs:"Asma persistente · VNI para crupe: 2 mg nebulização dose única" },
  // ─── Broncodilatadores ──────────────────────────────────────────────────────
  { id:"salbutamol",      cat:"Respiratório",nome:"Salbutamol (Albuterol)",      via:"INH (spray/MDI)",dose:"Por gravidade da crise", freq:"20/20 min × 3 (1ª hora)", max:"10 jatos/dose",obs:"Spray 100 mcg/jato via espaçador. Dose escalonada pela gravidade da crise — reavaliar a cada ciclo. Nebulização retirada por desuso.", jatos:[{grav:"Leve",jatos:"2–4",freq:"20/20 min × 3"},{grav:"Moderada",jatos:"6",freq:"20/20 min × 3"},{grav:"Grave",jatos:"10",freq:"20/20 min × 3"}] },
  { id:"ipratropio",      cat:"Respiratório",nome:"Brometo de Ipratrópio",       via:"NBZ",   dose:"0,25 mg (< 6 a) / 0,5 mg (≥ 6 a)", freq:"20/20 min × 3", max:"0,5 mg/dose", obs:"Associar ao salbutamol na asma moderada–grave · Não há dose pelo peso" },
  { id:"montelucaste",    cat:"Respiratório",nome:"Montelucaste",                via:"VO",    dose:"4 mg (1–5 a) · 5 mg (6–14 a)", freq:"1x/dia (noite)", max:"10 mg", obs:"Asma leve persistente, rinite alérgica · Atenção: risco de eventos neuropsiquiátricos (FDA 2020)" },
  // ─── Antihistamínicos ───────────────────────────────────────────────────────
  { id:"loratadina",      cat:"Antihistamínico", nome:"Loratadina",             via:"VO",    dose:"0,2 mg/kg/dia",      freq:"1x/dia",          max:"10 mg/dia", obs:"2–5 anos: 5 mg/dia · ≥ 6 anos: 10 mg/dia · Sem sedação · Siruposo 1 mg/mL", calc:{min:0.2,max:0.2,unidade:"dia",tomadas:[1],tetoMg:10,tetoTipo:"dia",susp:[{label:"Xarope 1 mg/mL",mgPer5:5,tomadas:1,freqLabel:"1x/dia"}]} },
  { id:"cetirizina",      cat:"Antihistamínico", nome:"Cetirizina",             via:"VO",    dose:"0,25 mg/kg/dose",    freq:"1–2x/dia",        max:"10 mg/dia", obs:"< 6 meses: 2,5 mg/dia · 6–12 m: 2,5 mg 12/12h · ≥ 6 a: 5–10 mg/dia · Mínima sedação", calc:{min:0.25,max:0.25,unidade:"dose",tomadasDiaMax:2,tetoMgDia:10,susp:[{label:"Solução 1 mg/mL",mgPerMl:1}]} },
  { id:"difenidramina",   cat:"Antihistamínico", nome:"Difenidramina (Benadryl)",via:"VO/IV",dose:"1 mg/kg/dose",       freq:"6/6h",            max:"50 mg/dose",obs:"Sedativo · IV em anafilaxia · Evitar < 2 anos (sedação paradoxal, risco de apneia)", calc:{min:1,max:1,unidade:"dose",tomadasDiaMax:4,tetoMg:50,tetoTipo:"dose",susp:[{label:"Xarope 2,5 mg/mL",mgPerMl:2.5}]} },
  { id:"hidroxizina",     cat:"Antihistamínico", nome:"Hidroxizina",            via:"VO",    dose:"1–2 mg/kg/dia",      freq:"8/8h–12/12h",     max:"50 mg/dose",obs:"Prurido intenso, urticária · Sedativo · Xarope 10 mg/5 mL", calc:{min:1,max:2,unidade:"dia",tomadas:[3,2],tetoMg:50,tetoTipo:"dose",susp:[{label:"Xarope 10 mg/5 mL",mgPer5:10,tomadas:3,freqLabel:"8/8h"}]} },
  // ─── Gastrointestinal ───────────────────────────────────────────────────────
  { id:"omeprazol",       cat:"Gastrointestinal", nome:"Omeprazol",             via:"VO",    dose:"1–2 mg/kg/dia",      freq:"1x/dia",          max:"40 mg/dia", obs:"30 min antes do café · Grânulos para lactentes · Uso > 1 ano preferencial", calc:{min:1,max:2,unidade:"dia",tomadas:[1],tetoMg:40,tetoTipo:"dia",susp:[]} },
  { id:"esomeprazol",     cat:"Gastrointestinal", nome:"Esomeprazol",           via:"VO/IV", dose:"0,5–1 mg/kg/dia",    freq:"1x/dia",          max:"40 mg/dia", obs:"< 20 kg: máx 20 mg · ≥ 20 kg: máx 40 mg · IV: infundir em 10–30 min", calc:{min:0.5,max:1,unidade:"dia",tomadas:[1],tetoMg:40,tetoTipo:"dia",tetoPorPeso:[{pesoMax:20,tetoMg:20},{pesoMax:999,tetoMg:40}],susp:[]} },
  { id:"ondansetrona",    cat:"Gastrointestinal", nome:"Ondansetrona",          via:"VO/IV", dose:"0,1–0,15 mg/kg/dose",freq:"8/8h prn",        max:"4 mg/dose < 40 kg · 8 mg ≥ 40 kg", obs:"Náusea e vômito · EV: infundir em 15 min · 1ª escolha em GEA", calc:{min:0.1,max:0.15,unidade:"dose",tomadasDiaMax:3,tetoPorPeso:[{pesoMax:40,tetoMg:4},{pesoMax:999,tetoMg:8}],susp:[]} },
  { id:"peg4000",         cat:"Gastrointestinal", nome:"Macrogol/PEG 4000",     via:"VO",    dose:"0,4–1,5 g/kg/dia",   freq:"1–2x/dia",        max:"Ajuste clínico",obs:"Constipação: manutenção 0,4–0,8 g/kg/dia · Desimpactação: 1–1,5 g/kg/dia × 3–6 dias" },
  { id:"lactulose",       cat:"Gastrointestinal", nome:"Lactulose",             via:"VO",    dose:"1–3 mL/kg/dia",      freq:"1–2x/dia",        max:"60 mL/dia", obs:"Alternativa ao PEG, especialmente < 1 ano · Xarope 667 mg/mL · Flatulência comum" },
  { id:"simeticona",      cat:"Gastrointestinal", nome:"Simeticona",            via:"VO",    dose:"20 mg/dose (< 2 a)", freq:"Após mamadas",     max:"240 mg/dia",obs:"Cólica funcional · Efficácia questionada em estudos · Segura · Gotas 75 mg/mL" },
  { id:"domperidona",     cat:"Gastrointestinal", nome:"Domperidona",           via:"VO",    dose:"0,25 mg/kg/dose",    freq:"3x/dia (a/c refeições)", max:"2,4 mg/kg/dia", obs:"DRGE refratária. ATENÇÃO: risco de QT longo. Não recomendada rotineiramente (ESPGHAN). Suspensa em vários países." },
  // ─── Neurológico / Antiepiléptico ───────────────────────────────────────────
  { id:"valproato_oral",  cat:"Neurológico",  nome:"Valproato (Ácido Valproico)", via:"VO",  dose:"15–60 mg/kg/dia",    freq:"8/8h ou 12/12h",  max:"60 mg/kg/dia",obs:"Dose inicial 10–15 mg/kg, titular. Xarope 50 mg/mL. Dosar nível sérico: 50–100 mcg/mL. Hepatotóxico < 2 anos.", calc:{min:15,max:60,unidade:"dia",tomadas:[2,3],tetoMgKgDia:60,susp:[{label:"Xarope 50 mg/mL",mgPer5:250,tomadas:2,freqLabel:"12/12h"}]} },
  { id:"fenobarbital_oral",cat:"Neurológico", nome:"Fenobarbital",              via:"VO",    dose:"3–5 mg/kg/dia",      freq:"1x/dia (noite)",   max:"200 mg/dia",obs:"Manutenção de epilepsia. Nível sérico: 15–40 mcg/mL. Sonolência, hiperatividade paradoxal.", calc:{min:3,max:5,unidade:"dia",tomadas:[1],tetoMg:200,tetoTipo:"dia",susp:[{label:"Gotas 40 mg/mL",mgPer5:200,tomadas:1,freqLabel:"1x/dia",gotas:true}]} },
  { id:"levetiracetam_oral",cat:"Neurológico",nome:"Levetiracetam",             via:"VO",    dose:"10–60 mg/kg/dia",    freq:"12/12h",           max:"3 g/dia",   obs:"Titular de 10 mg/kg/dia. Comprimido, solução 100 mg/mL. Efeito colateral comportamental.", calc:{min:10,max:60,unidade:"dia",tomadas:[2],tetoMg:3000,tetoTipo:"dia",susp:[{label:"Solução 100 mg/mL",mgPer5:500,tomadas:2,freqLabel:"12/12h"}]} },
  { id:"carbamazepina",   cat:"Neurológico",  nome:"Carbamazepina",             via:"VO",    dose:"10–20 mg/kg/dia",    freq:"8/8h ou 12/12h",   max:"1,2 g/dia", obs:"Epilepsia focal. Nível sérico: 4–12 mcg/mL. Indutor enzimático. Hemograma periódico.", calc:{min:10,max:20,unidade:"dia",tomadas:[2,3],tetoMg:1200,tetoTipo:"dia",susp:[{label:"Suspensão 20 mg/mL",mgPer5:100,tomadas:2,freqLabel:"12/12h"}]} },
  { id:"diazepam_oral",   cat:"Neurológico",  nome:"Diazepam (manutenção)",     via:"VO",    dose:"0,1–0,3 mg/kg/dose", freq:"8/8h prn",         max:"5 mg/dose", obs:"NÃO usar para prevenir convulsão febril: a profilaxia com anticonvulsivante não é recomendada (AAP/SBP) — a convulsão febril simples é benigna e a sedação pode mascarar sinais de infecção do SNC. Uso oral restrito a indicações de manutenção definidas pelo neurologista.", calc:{min:0.1,max:0.3,unidade:"dose",tomadasDiaMax:3,tetoMg:5,tetoTipo:"dose",susp:[]} },
  // ─── Antifúngico / Antiviral ────────────────────────────────────────────────
  { id:"fluconazol",      cat:"Antifúngico",  nome:"Fluconazol",                via:"VO/IV", dose:"3–12 mg/kg/dia",     freq:"1x/dia",           max:"400 mg/dia",obs:"Candida oral/esofágica: 3–6 mg/kg/dia. Meningite criptocócica: 12 mg/kg/dia." },
  { id:"nistatina",       cat:"Antifúngico",  nome:"Nistatina (oral)",          via:"VO",    dose:"100.000 UI/dose",     freq:"4–6x/dia após mamada", max:"—",   obs:"Candidíase oral em lactentes. 4–6 semanas. Aplicar com cotonete em bochechas e língua." },
  { id:"aciclovir_oral",  cat:"Antiviral",    nome:"Aciclovir oral",            via:"VO",    dose:"20 mg/kg/dose",       freq:"5x/dia",           max:"800 mg/dose",obs:"Varicela não complicada (> 12 a ou risco): iniciar < 24h do exantema. Herpes simples: 15 mg/kg/dia." },
  { id:"oseltamivir",     cat:"Antiviral",    nome:"Oseltamivir (Tamiflu)",     via:"VO",    dose:"3 mg/kg/dose (1–12 a)", freq:"12/12h × 5 dias", max:"75 mg/dose",obs:"Influenza A/B confirmada ou suspeita. Suspensão 12 mg/mL. Iniciar idealmente < 48h dos sintomas." },
  // ─── Vitaminas e Suplementos ────────────────────────────────────────────────
  { id:"vitamina_d",      cat:"Suplemento",   nome:"Vitamina D3",               via:"VO",    dose:"400–1.000 UI/dia",    freq:"1x/dia",           max:"4.000 UI/dia (profilaxia)", obs:"Profilaxia RN: 400 UI/dia. Deficiência: 1.000–3.000 UI/dia. Dosar 25(OH)D se suspeita de deficiência." },
  { id:"ferro",           cat:"Suplemento",   nome:"Sulfato Ferroso",           via:"VO",    dose:"3–6 mg/kg/dia (Fe elementar)", freq:"1–2x/dia", max:"60 mg/dia Fe elementar", obs:"Tratamento anemia: 3–6 mg/kg/dia. Profilaxia RNPT: 2 mg/kg/dia a partir de 1 mês. Jejum para melhor absorção." },
  { id:"zinc",            cat:"Suplemento",   nome:"Sulfato de Zinco",          via:"VO",    dose:"0,5–1 mg/kg/dia (Zn elementar)", freq:"1x/dia", max:"20 mg/dia", obs:"Diarreia aguda (OMS): 10–20 mg/dia × 10–14 dias. Deficiência. Atraso crescimento." },
  { id:"vit_a",           cat:"Suplemento",   nome:"Vitamina A (Megadose)",     via:"VO",    dose:"Dose única conforme faixa etária", freq:"A cada 6 meses", max:"200.000 UI", obs:"SUS: 100.000 UI (6–11 m) · 200.000 UI (1–4 a). Regiões endêmicas, sarampo grave, desnutrição." },
  // ─── Outros ─────────────────────────────────────────────────────────────────
  { id:"ibuprofeno_iv",   cat:"Analgésico",   nome:"Ibuprofeno IV (Caldolor)",  via:"IV",    dose:"10 mg/kg/dose",       freq:"6/6h–8/8h",        max:"40 mg/kg/dia",obs:"Indicado em contexto hospitalar · Infundir em 30 min · Fechamento CA em prematuro." },
  { id:"naloxona",        cat:"Antídoto",     nome:"Naloxona",                  via:"IV/IM/IN", dose:"0,01 mg/kg/dose",  freq:"Repetir 2–3 min", max:"0,1 mg/kg",  obs:"Intoxicação por opioides. IN: 0,1 mg/kg (máx 4 mg). Duração curta — monitorar reaparição de depressão." },
];
